showGrid: false

url: http://www.thecave.com
title: thecave
author: Kirby Turner
baseurl: ""
url: "http://www.thecave.com"
header-img: "img/home-bg.jpg"

# Social Sites
adn_username: kirbyt
twitter_username: kirbyt
github_username:  kirbyt
linkedin_username: kirbyturner

root: /

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section

permalink: /:year/:month/:day/:title/

# Category plugin (https://github.com/recurser/jekyll-plugins)
category_dir: category

exclude: [Rakefile, readme.md]
include: [.nojekyll, keybase.txt]
